---
archives:
- formats:
  - tar.gz
  id: default
  ids:
  - rgb-led
builds:
- binary: rgb-led
  env: [CGO_ENABLED=0]
  goarch:
  - amd64
  - arm64
  goos: [linux]
  id: rgb-led
  ldflags: "-s -w"
  main: ./main.go
project_name: rgb-led
version: 2
